# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "soj" ]
  pull_request:
    branches: [ "soj" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with: 
        version: 7
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build distribution
      run: pnpm run build
    - name: Create artifact
      run: tar --dereference --hard-dereference --directory dist/ -zcvf aqua-rank.tar.gz .
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: aqua-rank-node-${{ matrix.node-version }}
        path: aqua-rank.tar.gz
